version: "3.8"
services:
  urlib-b:
    container_name: urlib-b
    image: ${DOCKERHUB_USERNAME}/urlib
    volumes:
      - ./logs:/app/logs
    ports:
      - "8082:8080"
    restart: always

networks:
  default:
    external:
      name: urlib
