spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${{ secrets.MYSQL_URL }}
    username: ${{ secrets.MYSQL_USERNAME }}
    password: ${{ secrets.MYSQL_PASSWORD }}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: MYSQL_DB

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379
  security:
    jwt:
      access-token-expiry: 600 # 10 minutes
      refresh-token-expiry: 3600 # 1 hour
      secret-key: ${{ secrets.SECURITY_SECRET_KEY }}    # 32 bytes
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${{ secrets.KAKAO_CLIENT_ID }}  # rest api 키
            client-secret: ${{ secrets.KAKAO_CLIENT_SECRET }} # client secret 키
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_image
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
