version: "3.8"
services:
  urlib-b:
    container_name: urlib-b
    image: ${DOCKER_USERNAME}/urlib-server
    volumes:
      - ./logs:/app/logs
    ports:
      - "8082:8080"
    environment:
      - SECURITY_SECRET_KEY=${SECURITY_SECRET_KEY}
      - PROD_MYSQL_URL=${PROD_MYSQL_URL}
      - PROD_MYSQL_USERNAME=${PROD_MYSQL_USERNAME}
      - PROD_MYSQL_PASSWORD=${PROD_MYSQL_PASSWORD}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - PROD_REDIS_HOST=${PROD_REDIS_HOST}
      - PROD_REDIS_PORT=${PROD_REDIS_PORT}
    restart: always
